# Generated by Django 3.2.12 on 2022-04-21 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_archived', models.BooleanField(default=False)),
                ('is_unread', models.BooleanField(default=False)),
                ('companion', models.ForeignKey(on_delete=models.SET(users.models.User.get_default_deleted_user), related_name='chats_companion', to=settings.AUTH_USER_MODEL)),
                ('me', models.ForeignKey(default=users.models.User.get_default_deleted_user, on_delete=django.db.models.deletion.CASCADE, related_name='chats_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
