# Generated by Django 3.2.12 on 2022-04-21 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('body', models.TextField(max_length=1000, verbose_name='Message body')),
                ('recipient', models.ForeignKey(on_delete=models.SET(users.models.User.get_default_deleted_user), related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('recipient_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='chats.chat')),
                ('sender', models.ForeignKey(on_delete=models.SET(users.models.User.get_default_deleted_user), related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('sender_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='chats.chat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
